export const locales = ["en", "de", "es"] as const;
export type Locale = (typeof locales)[number];

const translations = {
  en: {
    catalog: "Catalog",
    close: "Close",
    contentLanguage: "Catalog source documents are maintained in English.",
    dark: "Dark",
    directory: "Directory",
    documents: "documents",
    edit: "Edit on GitHub",
    entries: "entries",
    language: "Language",
    light: "Light",
    menu: "Browse catalog",
    navigate: "navigate",
    next: "Next",
    notFoundDescription: "The document may have moved as the folder structure evolved.",
    notFoundTitle: "That convention is not in the catalog.",
    noResults: "No matching rules or documents.",
    open: "open",
    outline: "On this page",
    overview: "Overview",
    previous: "Previous",
    returnOverview: "Return to the overview",
    results: "results",
    rules: "rules",
    search: "Search conventions",
    searchHint: "Try a rule ID, technology, or phrase.",
    source: "Source",
    system: "System",
    theme: "Theme",
    hierarchyDescription: "Browse the catalog using the same hierarchy encoded by the repository.",
  },
  de: {
    catalog: "Katalog",
    close: "Schließen",
    contentLanguage: "Die Quelldokumente des Katalogs werden auf Englisch gepflegt.",
    dark: "Dunkel",
    directory: "Verzeichnis",
    documents: "Dokumente",
    edit: "Auf GitHub bearbeiten",
    entries: "Einträge",
    language: "Sprache",
    light: "Hell",
    menu: "Katalog durchsuchen",
    navigate: "navigieren",
    next: "Weiter",
    notFoundDescription: "Das Dokument wurde möglicherweise verschoben, als sich die Ordnerstruktur weiterentwickelte.",
    notFoundTitle: "Diese Konvention ist nicht im Katalog.",
    noResults: "Keine passenden Regeln oder Dokumente.",
    open: "öffnen",
    outline: "Auf dieser Seite",
    overview: "Übersicht",
    previous: "Zurück",
    returnOverview: "Zur Übersicht",
    results: "Ergebnisse",
    rules: "Regeln",
    search: "Konventionen suchen",
    searchHint: "Suche nach Regel-ID, Technologie oder Begriff.",
    source: "Quelle",
    system: "System",
    theme: "Design",
    hierarchyDescription: "Durchsuche den Katalog in derselben Hierarchie, die das Repository vorgibt.",
  },
  es: {
    catalog: "Catálogo",
    close: "Cerrar",
    contentLanguage: "Los documentos fuente del catálogo se mantienen en inglés.",
    dark: "Oscuro",
    directory: "Directorio",
    documents: "documentos",
    edit: "Editar en GitHub",
    entries: "entradas",
    language: "Idioma",
    light: "Claro",
    menu: "Explorar catálogo",
    navigate: "navegar",
    next: "Siguiente",
    notFoundDescription: "Es posible que el documento se haya movido al evolucionar la estructura de carpetas.",
    notFoundTitle: "Esa convención no está en el catálogo.",
    noResults: "No hay reglas o documentos coincidentes.",
    open: "abrir",
    outline: "En esta página",
    overview: "Resumen",
    previous: "Anterior",
    returnOverview: "Volver al resumen",
    results: "resultados",
    rules: "reglas",
    search: "Buscar convenciones",
    searchHint: "Prueba un ID de regla, tecnología o frase.",
    source: "Fuente",
    system: "Sistema",
    theme: "Tema",
    hierarchyDescription: "Explora el catálogo con la misma jerarquía codificada por el repositorio.",
  },
} satisfies Record<Locale, Record<string, string>>;

export type Copy = (typeof translations)[Locale];

export function getCopy(locale: Locale) {
  return translations[locale];
}
